#!/bin/bash

wget https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.16.tar.xz

#getting ready for compilation

tar xvJf linux-4.16.tar.xz
sudo apt-get install libncurses5-dev libncursesw5-dev
cd linux-4.16/
sudo make menuconfig


#compiling kernel
make

#module compilation
make modules


#moduule installation
sudo make modules_install


#new kernel installation
sudo make install
